spring.application.name=quantitymeasurementApp
spring.config.import=optional:file:.env[.properties]

# Database Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/quantity_measurement
spring.datasource.username=root
spring.datasource.password=tiger

# Spring JPA / Hibernate Config (Automatically creates/updates tables!)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=8080

# Google OAuth2 Credentials
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:YOUR_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:YOUR_GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

# JWT Secret Key (Must be a long, secure, Base64 string in production. This is just for dev!)
jwt.secret=${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=86400000 
# Expiration: 1 day in milliseconds