server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:5173"
              - "${FRONTEND_URL:*}"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: measurement-service
          uri: lb://measurement-service
          predicates:
            - Path=/api/v1/measurements/**
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/api/v1/auth/**, /oauth2/**, /login/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-server.railway.internal:8761/eureka/}
