server:
  port: ${PORT:8080}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:quantitymeasurementapp.railway.internal}
    prefer-ip-address: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
